dist: xenial
language: java
sudo: false
jdk: openjdk15
intall: true
aaddons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
  script:
    - mvn clean package sonar:sonar -P sonar
  cache:
    directories:
      - $HOME/.m2
      - $home/.sonar/cache

before_install:
  - chmod +x mvnw